# Welcome to Jekyll!
#

# Site settings
title: CoughDrop
description: |
  Communication is for Everyone.
  CoughDrop<br/> empowers people to make their voices heard.
owner: CoughDrop, Inc. # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@mycoughdrop.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.coughdrop.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/CoughDropAAC
  github: https://github.com/CoughDrop
  linkedin-square: https://www.linkedin.com/company/coughdrop
  facebook-official: https://facebook.com/CoughDropAAC
  google-plus-square: https://plus.google.com/+myCoughDropAAC
  #email: /contact/
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/c/myCoughDropAAC
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
